### ISSUE TITLE
linux无法使用插件

### ISSUE THREAD

**Issue by corvo007** [pcrbot/musewiki#1]
因为语音资源的路径是硬编码为`C:/Resources/xxx.wav`的，导致linux系统无法使用，因为并不存在这个路径。建议把硬编码的路径改为拼接的路径，即资源文件夹路径+语音的相对路径。
这一点可以使用`os.path`模块或者`pathlib`模块处理。

**Comment by Soung2279** [comment]
新版本应该已经修复了，更新内容的时候顺便检查了一下，将 ``[歌曲详细查询，动画查询和歌曲推送]`` 时使用的绝对路径进行了替换。
